# Generated by Django 5.2.17 on 2026-08-17 18:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Destinatário')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('template', models.CharField(max_length=255, verbose_name='Template')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Contexto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último Erro')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação por E-mail',
                'verbose_name_plural': 'Notificações por E-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
