# Generated by Django 5.2.17 on 2026-08-17 22:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_name', models.CharField(max_length=150, verbose_name='Nome do Responsável')),
                ('responsible_relationship', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('responsible_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone do Responsável')),
                ('chief_complaint', models.TextField(verbose_name='Queixa Principal / Motivo da Procura')),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='Diagnóstico')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Data do Diagnóstico')),
                ('diagnosing_professional', models.CharField(blank=True, max_length=255, verbose_name='Profissional/Instituição que Diagnosticou')),
                ('medical_history', models.TextField(blank=True, verbose_name='Histórico Médico (gestação, parto, saúde geral)')),
                ('family_history', models.TextField(blank=True, verbose_name='Histórico Familiar')),
                ('developmental_milestones', models.TextField(blank=True, verbose_name='Marcos do Desenvolvimento (motor, fala, social)')),
                ('communication_profile', models.TextField(blank=True, verbose_name='Comunicação (verbal, não-verbal, uso de CAA)')),
                ('sensory_profile', models.TextField(blank=True, verbose_name='Perfil Sensorial')),
                ('behaviors_of_concern', models.TextField(blank=True, verbose_name='Comportamentos de Interesse Clínico')),
                ('feeding_notes', models.TextField(blank=True, verbose_name='Alimentação')),
                ('sleep_notes', models.TextField(blank=True, verbose_name='Sono')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicações em Uso')),
                ('previous_therapies', models.TextField(blank=True, verbose_name='Terapias Anteriores/Atuais')),
                ('school_info', models.TextField(blank=True, verbose_name='Informações Escolares')),
                ('family_expectations', models.TextField(blank=True, verbose_name='Expectativas da Família')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='scheduling.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
        migrations.CreateModel(
            name='BehavioralGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Objetivo/Comportamento-Alvo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição/Operacionalização')),
                ('measurement_type', models.CharField(choices=[('FREQUENCY', 'Frequência (nº de ocorrências)'), ('DURATION', 'Duração (minutos)'), ('PERCENTAGE', 'Porcentagem de acertos (tentativas)'), ('INTENSITY', 'Intensidade (escala 1-5)')], max_length=20, verbose_name='Tipo de Medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_goals', to='scheduling.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo Comportamental',
                'verbose_name_plural': 'Objetivos Comportamentais',
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Valor (frequência/duração/intensidade)')),
                ('trials_correct', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acertos')),
                ('trials_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Tentativas')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_records', to='scheduling.appointment', verbose_name='Sessão/Agendamento')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scheduling.behavioralgoal', verbose_name='Objetivo')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Coleta',
                'verbose_name_plural': 'Registros de Coleta',
                'ordering': ['-appointment__session_datetime'],
            },
        ),
    ]
